// Generated by CoffeeScript 1.6.3
(function() {
  var range, square, _i, _results;

  range = (function() {
    _results = [];
    for (_i = 1; _i <= 100; _i++){ _results.push(_i); }
    return _results;
  }).apply(this);

  square = function(a) {
    return a * a;
  };

  console.log((function(a) {
    var item, _j, _len, _results1;
    _results1 = [];
    for (_j = 0, _len = range.length; _j < _len; _j++) {
      item = range[_j];
      _results1.push(a * a);
    }
    return _results1;
  }));

}).call(this);
